approach_name: GritLM
conda_env: benchmark_env_gritlm
module_path: "approaches/benchmark_approaches_src/GritLM"
class_name: GritLMEmbedder

embedding_model: ~
table_row_limit: 100
table_serialization_format: markdown   # markdown or csv, used by table-level embedding

supported_tasks:
  row_similarity_search:
    run_similarity_search_based_on: row_embeddings
  row_triplet_evaluation: {}
  column_similarity_search:
    run_similarity_search_based_on: column_embeddings
  cell_similarity_search: {}
  table_retrieval: {}
  table_similarity_search: {}
  table_shuffling: {}
  table_type_detection: {}
  predictive_ml:
    run_task_based_on: row_embeddings
  schema_linking: {}
  value_linking: {}
  column_type_annotation: {}
