approach_name: hashing
conda_env: benchmark_env
module_path: "approaches/benchmark_approaches_src/hashing"
class_name: HashingTableEmbedder

n_features: 32768
table_row_limit: -1      # -1 for no limit

supported_tasks:
  table_retrieval: {}
  table_shuffling: {}
  table_type_detection: {}
