# @package _global_
dataset_name: wikidata_books

variations:
  # missing_values: [0.0, 0.1, 0.2]
  number_of_cols: [4, 9, 29, 123, 281]
  column_naming: [simple, complex, numbered, combined]
  #n_numerical_cols: [2, 4, 6]