benchmark_output_dir: main_experiments
approaches:
  - name: GritLM
    params:
      embedding_model: GritLM/GritLM-7B

  - name: GritLM
    params:
      embedding_model: GritLM/GritLM-7B
      table_row_limit: 0  # "Just Schema" variant for the paper's table_retrieval comparison
    tasks: [table_retrieval]
