benchmark_output_dir: revision_experiments

tasks:
  - table_retrieval

approaches:
  - name: GritLM
    params:
      embedding_model: GritLM/GritLM-7B

  - name: sentence_transformer
    params:
      embedding_model: all-MiniLM-L6-v2

  - name: sentence_transformer
    params:
      embedding_model: ibm-granite/granite-embedding-english-r2

  - name: hytrel

  - name: tabbie

  - name: tabert

  - name: tuta
