benchmark_output_dir: just_testing
log_level: DEBUG
approaches:
  - name: sentence_transformer
    params:
      embedding_model: all-MiniLM-L6-v2
      table_row_limit: 100
    tasks:
      - row_similarity_search
      - row_triplet_evaluation
      - column_similarity_search
      - column_type_annotation
      - predictive_ml
    task_datasets:
      row_similarity_search:
        - Amazon-Google
      row_triplet_evaluation:
        - wikidata_books
      column_similarity_search:
        - valentine
        - opendata
      column_type_annotation:
        - sotab
      predictive_ml:
        - credit-g
        - anneal
        - healthcare_insurance_expenses
    task_params:
      column_similarity_search:
        test_case_limit: 5
      column_type_annotation:
        test_case_limit: 5
