benchmark_output_dir: just_testing
log_level: DEBUG
approaches:
  - name: tarte
    tasks:
     # - row_similarity_search
     # - more_similar_than
     # - table_shuffling
      - column_similarity_search
      - cell_task
     # - predictive_ml
    task_datasets:
      row_similarity_search:
        - Amazon-Google
      more_similar_than:
        - wikidata_books
      table_shuffling:
        - fetaqa@@v0
      column_similarity_search:
        - valentine
      cell_task:
        - s2abel@clean
      predictive_ml:
        - credit-g
        - anneal
        - healthcare_insurance_expenses
    task_params:
      column_similarity_search:
        test_case_limit: 5
      column_type_annotation:
        test_case_limit: 5
      cell_task:
        test_case_limit: 5
