benchmark_output_dir: just_testing
log_level: DEBUG
approaches:
  - name: tabert
    tasks:
      - row_similarity_search
      - more_similar_than
      - column_similarity_search
      - predictive_ml
    task_datasets:
      row_similarity_search:
        - Amazon-Google
      more_similar_than:
        - wikidata_books
      column_similarity_search:
        - valentine
        - opendata
      predictive_ml:
        - credit-g
        - anneal
        - healthcare_insurance_expenses
    task_params:
      column_similarity_search:
        test_case_limit: 5
