benchmark_output_dir: value_linking_experiments
task_params:
  max_queries: 100
approaches:
  - name: sentence_transformer
    params:
      embedding_model: all-MiniLM-L6-v2
    tasks:
      - value_linking
    task_params:
      value_linking:
        query_mode: full_nl
  - name: sentence_transformer
    params:
      embedding_model: all-MiniLM-L6-v2
    tasks:
      - value_linking
    task_params:
      value_linking:
        query_mode: extracted_values
