approach_name: contexttab

module_path: "approaches/benchmark_approaches_src/contexttab"
class_name: ConTextTabEmbedder

_target_: approaches.benchmark_approaches_src.contexttab.approach.ConTextTabEmbedder

# Model parameters
bagging: 1
max_context_size: 2048
test_chunk_size: 1000
device: "auto"

# Benchmark tasks configuration
benchmark_tasks:
  predictive_ml:
    task_parameters:
      run_task_based_on: "custom_predictiveML_model"
